### PR TITLE
Update Bluetooth section

### PR DESCRIPTION
**Pull request by zssz**
Add C019 16-bit Bluetooth UUID
Add Android as a "bridge" workaround for iOS-iOS background discoverability issue

### CODE REVIEW

**Comment by hdevalence** [comment]
Thanks!

@zssz separately to this PR (merging it now), would you be willing to write a little bit more of an introduction / overview of the concepts in the Bluetooth part? Right now the content is just copied from the Google doc, which assumed knowledge of Bluetooth.

**Comment by zssz** [comment]
Yes, I'll do that. Stay tuned.

**Comment by hdevalence** [comment]
Awesome! I'll make an issue to keep track.

**Comment by pzboyz** [comment]
The value 0xC019 is a 16bit UUID and is therefore its usage is controlled by the BTSIG.

Has the TCN Coalition obtained permission to us this value from BTSIG? If not, then devices using this value are not conforming to BTSIG qualification requirements and the implications that may have.

**Comment by scottleibrand** [comment]
Not yet AFAIK. What implications would that have?

**Pull request merged**
